### ISSUE TITLE
Wrong documentId namespace 

### ISSUE THREAD

**Issue by thanray** [Currence-Online/iDIN-libraries-java#4]
To document signing, one should add hash value of the document, as AttributeType: 

In the lib it is used: 

   public static final String DocumentId = "urn:nl:bvn:bankid:1.0:consumer.documentID";

but in the merchant implmentation documentation it is used: 
    public static final String DocumentId = "urn:nl:bvn:bankid:1.0:merchant.documentID";

DOC: 
https://betaalvereniging.atlassian.net/wiki/spaces/IIDIFMD/pages/588284049/iDIN+Merchant+Implemention+Guide+EN

**Comment by grigoresc** [comment]
Fixed.
Thank you for your feedback.
