### ISSUE TITLE
Not able to compile the java project

### ISSUE THREAD

**Issue by thanray** [Currence-Online/iDIN-libraries-java#5]
jdk: 
openjdk version ### ### "1.8.0_222"

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
**[ERROR] /home/karraj/libs/iDIN-libraries-java/Java/library/src/net/bankid/merchant/library/XmlProcessor.java:[242,107] package org.jcp.xml.dsig.internal.dom does not exist**
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.341 s
[INFO] Finished at: 2019-10-01T10:18:56+02:00
[INFO] ------------------------------------------------------------------------

**Comment by grigoresc** [comment]
Fixed.
Thank you for your feedback.
